// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pR5bvw2qHzxLEoDYFfc4Gw
// Component: BOhrI2DmHs
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_simple_light_landing_page.module.css"; // plasmic-import: pR5bvw2qHzxLEoDYFfc4Gw/projectcss
import * as sty from "./PlasmicMakeThings.module.css"; // plasmic-import: BOhrI2DmHs/css

export type PlasmicMakeThings__VariantMembers = {
  color: "red" | "blue";
};

export type PlasmicMakeThings__VariantsArgs = {
  color?: MultiChoiceArg<"red" | "blue">;
};

type VariantPropType = keyof PlasmicMakeThings__VariantsArgs;
export const PlasmicMakeThings__VariantProps = new Array<VariantPropType>(
  "color"
);

export type PlasmicMakeThings__ArgsType = {};
type ArgPropType = keyof PlasmicMakeThings__ArgsType;
export const PlasmicMakeThings__ArgProps = new Array<ArgPropType>();

export type PlasmicMakeThings__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMakeThingsProps {
  color?: MultiChoiceArg<"red" | "blue">;
  className?: string;
}

function PlasmicMakeThings__RenderFunc(props: {
  variants: PlasmicMakeThings__VariantsArgs;
  args: PlasmicMakeThings__ArgsType;
  overrides: PlasmicMakeThings__OverridesType;
  dataFetches?: PlasmicMakeThings__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__color_blue]: hasVariant(variants, "color", "blue"),
          [sty.root__color_red]: hasVariant(variants, "color", "red")
        }
      )}
    >
      {"Make your things"}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMakeThings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMakeThings__VariantsArgs;
    args?: PlasmicMakeThings__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMakeThings__Fetches;
  } & Omit<PlasmicMakeThings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMakeThings__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMakeThings__ArgProps,
      internalVariantPropNames: PlasmicMakeThings__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMakeThings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMakeThings";
  } else {
    func.displayName = `PlasmicMakeThings.${nodeName}`;
  }
  return func;
}

export const PlasmicMakeThings = Object.assign(
  // Top-level PlasmicMakeThings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMakeThings
    internalVariantProps: PlasmicMakeThings__VariantProps,
    internalArgProps: PlasmicMakeThings__ArgProps
  }
);

export default PlasmicMakeThings;
/* prettier-ignore-end */
