// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pR5bvw2qHzxLEoDYFfc4Gw
// Component: DARnZLG6rssWW
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MakeThings from "../../MakeThings"; // plasmic-import: BOhrI2DmHs/component
import Wonderfull from "../../Wonderfull"; // plasmic-import: x7QwHx-Jf7/component
import LinkButton from "../../LinkButton"; // plasmic-import: YrkIuHbKh3C2RJ/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 176-5-k3VAllNq/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_simple_light_landing_page.module.css"; // plasmic-import: pR5bvw2qHzxLEoDYFfc4Gw/projectcss
import * as sty from "./PlasmicTopSection.module.css"; // plasmic-import: DARnZLG6rssWW/css

import heroImageKyx3OmCxqfh8Sb from "./images/heroImage.png"; // plasmic-import: kyx3omCxqfh8Sb/picture

export type PlasmicTopSection__VariantMembers = {};

export type PlasmicTopSection__VariantsArgs = {};
type VariantPropType = keyof PlasmicTopSection__VariantsArgs;
export const PlasmicTopSection__VariantProps = new Array<VariantPropType>();

export type PlasmicTopSection__ArgsType = {};
type ArgPropType = keyof PlasmicTopSection__ArgsType;
export const PlasmicTopSection__ArgProps = new Array<ArgPropType>();

export type PlasmicTopSection__OverridesType = {
  root?: p.Flex<"div">;
  makeThings?: p.Flex<typeof MakeThings>;
  wonderfull?: p.Flex<typeof Wonderfull>;
  link?: p.Flex<"a">;
  img?: p.Flex<"img">;
};

export interface DefaultTopSectionProps {
  className?: string;
}

function PlasmicTopSection__RenderFunc(props: {
  variants: PlasmicTopSection__VariantsArgs;
  args: PlasmicTopSection__ArgsType;
  overrides: PlasmicTopSection__OverridesType;
  dataFetches?: PlasmicTopSection__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox___9LbMb)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.freeBox__jq0Up)}
        >
          <div className={classNames(defaultcss.all, sty.freeBox__fsL83)}>
            <MakeThings
              data-plasmic-name={"makeThings"}
              data-plasmic-override={overrides.makeThings}
              className={classNames("__wab_instance", sty.makeThings)}
            />

            <Wonderfull
              data-plasmic-name={"wonderfull"}
              data-plasmic-override={overrides.wonderfull}
              className={classNames("__wab_instance", sty.wonderfull)}
              forcefield={["fo", "things"]}
              singleSlect={"two" as const}
            >
              {"Wonderfull"}
            </Wonderfull>
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.freeBox__cxJ8Q
            )}
          >
            {
              "Our landing page template works on all devices, so you only have to set it up once, and get beautiful results forever."
            }
          </div>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.freeBox__upe7X)}
        >
          <LinkButton
            className={classNames("__wab_instance", sty.linkButton__dlqfl)}
            text={"Start free trial"}
            type={"solidBlue" as const}
          />

          <LinkButton
            className={classNames("__wab_instance", sty.linkButton__mQgs0)}
            text={"Learn more"}
            type={"solidBlack" as const}
          />
        </p.Stack>

        <a
          data-plasmic-name={"link"}
          data-plasmic-override={overrides.link}
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.link
          )}
          href={"https://www.plasmic.app/" as const}
        >
          {"Some link text"}
        </a>

        <div className={classNames(defaultcss.all, sty.freeBox__jix1F)}>
          {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
            <img
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(defaultcss.img, sty.img)}
              role={"img"}
              src={heroImageKyx3OmCxqfh8Sb}
            />
          ) : null}
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "makeThings", "wonderfull", "link", "img"],
  makeThings: ["makeThings"],
  wonderfull: ["wonderfull"],
  link: ["link"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  makeThings: typeof MakeThings;
  wonderfull: typeof Wonderfull;
  link: "a";
  img: "img";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTopSection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTopSection__VariantsArgs;
    args?: PlasmicTopSection__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTopSection__Fetches;
  } & Omit<PlasmicTopSection__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTopSection__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTopSection__ArgProps,
      internalVariantPropNames: PlasmicTopSection__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTopSection__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTopSection";
  } else {
    func.displayName = `PlasmicTopSection.${nodeName}`;
  }
  return func;
}

export const PlasmicTopSection = Object.assign(
  // Top-level PlasmicTopSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    makeThings: makeNodeComponent("makeThings"),
    wonderfull: makeNodeComponent("wonderfull"),
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicTopSection
    internalVariantProps: PlasmicTopSection__VariantProps,
    internalArgProps: PlasmicTopSection__ArgProps
  }
);

export default PlasmicTopSection;
/* prettier-ignore-end */
