// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pR5bvw2qHzxLEoDYFfc4Gw
// Component: x7QwHx-Jf7
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_simple_light_landing_page.module.css"; // plasmic-import: pR5bvw2qHzxLEoDYFfc4Gw/projectcss
import * as sty from "./PlasmicWonderfull.module.css"; // plasmic-import: x7QwHx-Jf7/css

export type PlasmicWonderfull__VariantMembers = {
  alternate: "alternate";
  foo: "foo";
  forcefield: "things" | "fo";
  singleSlect: "obe" | "two";
};

export type PlasmicWonderfull__VariantsArgs = {
  alternate?: SingleBooleanChoiceArg<"alternate">;
  foo?: SingleBooleanChoiceArg<"foo">;
  forcefield?: MultiChoiceArg<"things" | "fo">;
  singleSlect?: SingleChoiceArg<"obe" | "two">;
};

type VariantPropType = keyof PlasmicWonderfull__VariantsArgs;
export const PlasmicWonderfull__VariantProps = new Array<VariantPropType>(
  "alternate",
  "foo",
  "forcefield",
  "singleSlect"
);

export type PlasmicWonderfull__ArgsType = {
  children?: React.ReactNode;
  color?: string;
};

type ArgPropType = keyof PlasmicWonderfull__ArgsType;
export const PlasmicWonderfull__ArgProps = new Array<ArgPropType>(
  "children",
  "color"
);

export type PlasmicWonderfull__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultWonderfullProps {
  children?: React.ReactNode;
  color?: string;
  alternate?: SingleBooleanChoiceArg<"alternate">;
  foo?: SingleBooleanChoiceArg<"foo">;
  forcefield?: MultiChoiceArg<"things" | "fo">;
  singleSlect?: SingleChoiceArg<"obe" | "two">;
  className?: string;
}

function PlasmicWonderfull__RenderFunc(props: {
  variants: PlasmicWonderfull__VariantsArgs;
  args: PlasmicWonderfull__ArgsType;
  overrides: PlasmicWonderfull__OverridesType;
  dataFetches?: PlasmicWonderfull__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__alternate]: hasVariant(variants, "alternate", "alternate"),
        [sty.root__foo]: hasVariant(variants, "foo", "foo")
      })}
    >
      {p.renderPlasmicSlot({
        defaultContents: "wonderful",
        value: args.children,
        className: classNames(sty.slotChildren, {
          [sty.slotChildren__alternate]: hasVariant(
            variants,
            "alternate",
            "alternate"
          ),
          [sty.slotChildren__foo]: hasVariant(variants, "foo", "foo"),
          [sty.slotChildren__forcefield_fo]: hasVariant(
            variants,
            "forcefield",
            "fo"
          ),
          [sty.slotChildren__forcefield_things]: hasVariant(
            variants,
            "forcefield",
            "things"
          ),
          [sty.slotChildren__singleSlect_obe]: hasVariant(
            variants,
            "singleSlect",
            "obe"
          ),
          [sty.slotChildren__singleSlect_two]: hasVariant(
            variants,
            "singleSlect",
            "two"
          )
        })
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWonderfull__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWonderfull__VariantsArgs;
    args?: PlasmicWonderfull__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicWonderfull__Fetches;
  } & Omit<PlasmicWonderfull__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWonderfull__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWonderfull__ArgProps,
      internalVariantPropNames: PlasmicWonderfull__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicWonderfull__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWonderfull";
  } else {
    func.displayName = `PlasmicWonderfull.${nodeName}`;
  }
  return func;
}

export const PlasmicWonderfull = Object.assign(
  // Top-level PlasmicWonderfull renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicWonderfull
    internalVariantProps: PlasmicWonderfull__VariantProps,
    internalArgProps: PlasmicWonderfull__ArgProps
  }
);

export default PlasmicWonderfull;
/* prettier-ignore-end */
